 apiVersion: apps/v1
 kind: Deployment
 metadata:
   labels:
      app: flasknode
      env: qa
   name: flasknode
   namespace: mlapi
 spec:
   replicas: 5
   selector:
     matchLabels:
       app: flasknode
   template:
     metadata:
       labels:
         app: flasknode
         env: qa
     spec:
       containers:
       - name: flasknode
         image: us.icr.io/ibm-kct/app:latest
         imagePullPolicy: Always
         ports:
         - containerPort: 5000
           protocol: TCP
       imagePullSecrets:
       - name: all-icr-io