 apiVersion: v1
 kind: Service
 metadata:
   name: flasknode
   labels:
    app: flasknode
   namespace: mlapi
 spec:
   type: LoadBalancer
   ports:
   - port: 5000
     targetPort: 5000
   selector:
     app: flasknode